config-sparse:
  modules:
    ai-ox-tethers:
      config:
        oxtethers:
          enabled:
            contents:
              suggested-value: true
          parameters:
            maxOxTethers:
              contents:
                suggested-value: 10
            dynamicMaxOxTethers:
              contents:
                suggested-value: 10
            maximumOxTethersPerQuarry:
              contents:
                suggested-value: 4
            thresholdStoneLoad:
              contents:
                suggested-value: 10
    ucp2-legacy:
      config:
        ai_access:
          enabled:
            contents:
              suggested-value: true
        ai_assaultswitch:
          enabled:
            contents:
              suggested-value: true
        ai_buywood:
          enabled:
            contents:
              suggested-value: true
        ai_defense:
          enabled:
            contents:
              suggested-value: true
        ai_fix_crusader_archers_pitch:
          enabled:
            contents:
              suggested-value: true
        ai_fix_laddermen_with_enclosed_keep:
          enabled:
            contents:
              suggested-value: true
        ai_nosleep:
          enabled:
            contents:
              suggested-value: true
        ai_rebuild:
          enabled:
            contents:
              suggested-value: true
        ai_towerengines:
          enabled:
            contents:
              suggested-value: true
        ai_housing:
          build_housing:
            contents:
              suggested-value:
                enabled: true
                sliderValue: 5
          campfire_housing:
            contents:
              suggested-value:
                enabled: true
                sliderValue: 10
          delete_housing:
            enabled:
              contents:
                suggested-value: true
        ai_resources_rebuy:
          flour:
            contents:
              suggested-value:
                enabled: true
                sliderValue: 1
          iron:
            contents:
              suggested-value:
                enabled: true
                sliderValue: 1
          wood:
            contents:
              suggested-value:
                enabled: true
                sliderValue: 1
        ai_demolish:
          ai_demolish_walls:
            enabled:
              contents:
                suggested-value: true
          ai_demolish_trapped:
            enabled:
              contents:
                suggested-value: true
          ai_demolish_eco:
            enabled:
              contents:
                suggested-value: true
        ai_addattack:
          contents:
            suggested-value:
              enabled: true
              choice: relative
              choices:
                absolute:
                  slider: 5
                relative:
                  slider: 1
        ai_attacklimit:
          contents:
            suggested-value:
              enabled: true
              sliderValue: 3000
        ai_attackwave:
          contents:
            suggested-value:
              enabled: true
              sliderValue: 15
        ai_recruitstate_initialtimer:
          contents:
            suggested-value:
              enabled: true
              sliderValue: 0
        fix_apple_orchard_build_size:
          enabled:
            contents:
              suggested-value: true
        o_healer:
          enabled:
            contents:
              suggested-value: true
        o_responsivegates:
          enabled:
            contents:
              suggested-value: true
        u_arabwall:
          enabled:
            contents:
              suggested-value: true
        o_fix_map_sending:
          enabled:
            contents:
              suggested-value: true
        o_fix_rapid_deletion_bug:
          enabled:
            contents:
              suggested-value: true
        o_fix_baker_disappear:
          enabled:
            contents:
              suggested-value: true
        o_fix_fletcher_bug:
          enabled:
            contents:
              suggested-value: true
        o_fix_ladderclimb:
          enabled:
            contents:
              suggested-value: true
        o_fix_moat_digging_unit_disappearing:
          enabled:
            contents:
              suggested-value: true
        o_restore_arabian_engineer_speech:
          enabled:
            contents:
              suggested-value: true
        u_fireballistafix:
          enabled:
            contents:
              suggested-value: true
        u_fix_applefarm_blocking:
          enabled:
            contents:
              suggested-value: true
        u_fix_lord_animation_stuck_movement:
          enabled:
            contents:
              suggested-value: true
        u_tanner_fix:
          enabled:
            contents:
              suggested-value: true
        o_change_siege_engine_spawn_position_catapult:
          enabled:
            contents:
              suggested-value: false
        o_increase_path_update_tick_rate:
          enabled:
            contents:
              suggested-value: true
        o_onlyai:
          enabled:
            contents:
              suggested-value: true
        o_override_identity_menu:
          enabled:
            contents:
              suggested-value: true
        o_playercolor:
          contents:
            suggested-value:
              enabled: false
              choice: red
        o_xtreme:
          enabled:
            contents:
              suggested-value: true
        o_armory_marketplace_weapon_order_fix:
          enabled:
            contents:
              suggested-value: false
        o_fast_placing:
          enabled:
            contents:
              suggested-value: true
        o_default_multiplayer_speed:
          contents:
            suggested-value:
              enabled: true
              sliderValue: 50
        o_engineertent:
          enabled:
            contents:
              suggested-value: true
        o_gamespeed:
          enabled:
            contents:
              suggested-value: true
        o_keys:
          enabled:
            contents:
              suggested-value: true
        o_moatvisibility:
          enabled:
            contents:
              suggested-value: true
    graphicsApiReplacer:
      config:
        graphic:
          vsync:
            contents:
              suggested-value: true
    running-units:
      config:
        macemen:
          running:
            general:
              contents:
                suggested-value: true
            ai:
              contents:
                suggested-value: aic_walk_if_not_defined
        slingers:
          running:
            general:
              contents:
                suggested-value: true
            ai:
              contents:
                suggested-value: aic_walk_if_not_defined
        slaves:
          running:
            general:
              contents:
                suggested-value: true
            ai:
              contents:
                suggested-value: aic_walk_if_not_defined
        spearmen:
          running:
            general:
              contents:
                suggested-value: false
            ai:
              contents:
                suggested-value: aic_walk_if_not_defined
    startResources:
      config:
        startGold:
          normal:
            noAdvantage:
              human:
                contents:
                  suggested-value: 0
              computer:
                contents:
                  suggested-value: 0
            minorHumanAdvantage:
              human:
                contents:
                  suggested-value: 500
              computer:
                contents:
                  suggested-value: 500
            majorHumanAdvantage:
              human:
                contents:
                  suggested-value: 1000
              computer:
                contents:
                  suggested-value: 1000
            minorComputerAdvantage:
              human:
                contents:
                  suggested-value: 0
              computer:
                contents:
                  suggested-value: 500
            majorComputerAdvantage:
              human:
                contents:
                  suggested-value: 0
              computer:
                contents:
                  suggested-value: 2000
          crusader:
            majorHumanAdvantage:
              human:
                contents:
                  suggested-value: 1000
              computer:
                contents:
                  suggested-value: 1000
            minorHumanAdvantage:
              human:
                contents:
                  suggested-value: 500
              computer:
                contents:
                  suggested-value: 500
            noAdvantage:
              human:
                contents:
                  suggested-value: 0
              computer:
                contents:
                  suggested-value: 0
            minorComputerAdvantage:
              human:
                contents:
                  suggested-value: 0
              computer:
                contents:
                  suggested-value: 500
            majorComputerAdvantage:
              human:
                contents:
                  suggested-value: 0
              computer:
                contents:
                  suggested-value: 2000
          deathmatch:
            noAdvantage:
              human:
                contents:
                  suggested-value: 0
              computer:
                contents:
                  suggested-value: 0
            minorHumanAdvantage:
              human:
                contents:
                  suggested-value: 500
              computer:
                contents:
                  suggested-value: 500
            majorHumanAdvantage:
              human:
                contents:
                  suggested-value: 1000
              computer:
                contents:
                  suggested-value: 1000
            minorComputerAdvantage:
              human:
                contents:
                  suggested-value: 0
              computer:
                contents:
                  suggested-value: 500
            majorComputerAdvantage:
              human:
                contents:
                  suggested-value: 0
              computer:
                contents:
                  suggested-value: 2000
        startGoods:
          normal:
            bread:
              contents:
                suggested-value: 15
            cheese:
              contents:
                suggested-value: 15
            meat:
              contents:
                suggested-value: 15
            fruit:
              contents:
                suggested-value: 15
            iron:
              contents:
                suggested-value: 5
            stone:
              contents:
                suggested-value: 36
            wood:
              contents:
                suggested-value: 120
          crusader:
            stone:
              contents:
                suggested-value: 36
            wood:
              contents:
                suggested-value: 120
            bread:
              contents:
                suggested-value: 15
            cheese:
              contents:
                suggested-value: 15
            meat:
              contents:
                suggested-value: 15
            fruit:
              contents:
                suggested-value: 15
            iron:
              contents:
                suggested-value: 5
          deathmatch:
            wood:
              contents:
                suggested-value: 240
            hop:
              contents:
                suggested-value: 10
            stone:
              contents:
                suggested-value: 72
            iron:
              contents:
                suggested-value: 10
            pitch:
              contents:
                suggested-value: 10
            cheese:
              contents:
                suggested-value: 25
            meat:
              contents:
                suggested-value: 25
            fruit:
              contents:
                suggested-value: 25
            beer:
              contents:
                suggested-value: 10
            bread:
              contents:
                suggested-value: 25
            flour:
              contents:
                suggested-value: 10
    aiSwapper:
      config:
        menu:
          contents:
            suggested-value:
              snake:
                - name: ApeX-AI-Snake
                  root: ucp/plugins/Ascension-AI-Tournament/resources/ai/Snake/
                  control:
                    aic: true
                    aiv: true
                    lord: true
                    startTroops: true
              richard:
                - name: ApeX-AI-Richard
                  root: ucp/plugins/Ascension-AI-Tournament/resources/ai/Richard/
                  control:
                    aic: true
                    aiv: true
                    lord: true
                    startTroops: true
        defaultLanguage:
          contents:
            suggested-value: null
        ai:
          richard:
            aic:
              contents:
                suggested-value:
                  name: ApeX-AI-Richard
                  root: ucp/plugins/Ascension-AI-Tournament/resources/ai/Richard/
                  active: true
            aiv:
              contents:
                suggested-value:
                  name: ApeX-AI-Richard
                  root: ucp/plugins/Ascension-AI-Tournament/resources/ai/Richard/
                  active: true
            lord:
              contents:
                suggested-value:
                  name: ApeX-AI-Richard
                  root: ucp/plugins/Ascension-AI-Tournament/resources/ai/Richard/
                  active: true
            startTroops:
              contents:
                suggested-value:
                  name: ApeX-AI-Richard
                  root: ucp/plugins/Ascension-AI-Tournament/resources/ai/Richard/
                  active: true
          snake:
            aic:
              contents:
                suggested-value:
                  name: ApeX-AI-Snake
                  root: ucp/plugins/Ascension-AI-Tournament/resources/ai/Snake/
                  active: true
            aiv:
              contents:
                suggested-value:
                  name: ApeX-AI-Snake
                  root: ucp/plugins/Ascension-AI-Tournament/resources/ai/Snake/
                  active: true
            lord:
              contents:
                suggested-value:
                  name: ApeX-AI-Snake
                  root: ucp/plugins/Ascension-AI-Tournament/resources/ai/Snake/
                  active: true
            startTroops:
              contents:
                suggested-value:
                  name: ApeX-AI-Snake
                  root: ucp/plugins/Ascension-AI-Tournament/resources/ai/Snake/
                  active: true
  plugins:
    Ascension-AI-Balance:
      config: {}
meta:
  version: 1.0.0
